### ISSUE TITLE
Hackathon/live coding session dataset (ProPL #11)

### ISSUE THREAD

**Issue by suhailshergill** [suhailshergill/ProPL-meetup#16]
Let's work together to come up with some datasets and options. I'm creating a template/checklist below. It would be great if everyone responds with those details in comments (one comment per dataset, to keep this manageable). Note that the below is not an exhaustive list, so if you see a need for more specifics, include them in your response.
- name/description
- is the data publicly available? if so, a link/reference to it.
- how many columns/attributes?
- how many rows?
- what's the density/sparsity?

Please show your votes on the submissions below by using the :+1: reaction (available by clicking on the smiley face in the top right corner of every comment)

**WINNING DATASET**
- data from the [kaggle titanic competition](https://www.kaggle.com/c/titanic). we also have some reference explorations on this dataset:
  - https://github.com/agconti/kaggle-titanic
  - http://wiekvoet.blogspot.ca/2015/07/predicting-titanic-deaths-on-kaggle.html and other blogs in the series. specifically http://wiekvoet.blogspot.ca/2015/09/predicting-titanic-deaths-on-kaggle-vi.html and https://www.r-bloggers.com/predicting-titanic-deaths-on-kaggle-vii-more-stan/ tries stan
  - https://www.kaggle.com/mrisdal/titanic/exploring-survival-on-the-titanic with a [reference submission](https://www.kaggle.com/benhamner/titanic/random-forest-benchmark-r/code) (one of many)
- **link to data:** a copy of the data can be found [here](https://github.com/agconti/kaggle-titanic/tree/master/data)
- **columns:** 11
- **rows:** 891
- **density/sparsity:** most attributes seem to have values for most entries. a notable exception is the column titled `Cabin`
- **a [description of the data](https://www.kaggle.com/c/titanic/data)**
  
  ```
  VARIABLE DESCRIPTIONS:
  survival        Survival
              (0 = No; 1 = Yes)
  pclass          Passenger Class
              (1 = 1st; 2 = 2nd; 3 = 3rd)
  name            Name
  sex             Sex
  age             Age
  sibsp           Number of Siblings/Spouses Aboard
  parch           Number of Parents/Children Aboard
  ticket          Ticket Number
  fare            Passenger Fare
  cabin           Cabin
  embarked        Port of Embarkation
              (C = Cherbourg; Q = Queenstown; S = Southampton)
  
  SPECIAL NOTES:
  Pclass is a proxy for socio-economic status (SES)
  1st ~ Upper; 2nd ~ Middle; 3rd ~ Lower
  
  Age is in Years; Fractional if Age less than One (1)
  If the Age is Estimated, it is in the form xx.5
  
  With respect to the family relation variables (i.e. sibsp and parch)
  some relations were ignored.  The following are the definitions used
  for sibsp and parch.
  
  Sibling:  Brother, Sister, Stepbrother, or Stepsister of Passenger Aboard Titanic
  Spouse:   Husband or Wife of Passenger Aboard Titanic (Mistresses and Fiances Ignored)
  Parent:   Mother or Father of Passenger Aboard Titanic
  Child:    Son, Daughter, Stepson, or Stepdaughter of Passenger Aboard Titanic
  
  Other family relatives excluded from this study include cousins,
  nephews/nieces, aunts/uncles, and in-laws.  Some children travelled
  only with a nanny, therefore parch=0 for them.  As well, some
  travelled with very close friends or neighbors in a village, however,
  the definitions do not support such relations.
  ```

**Comment by suhailshergill** [comment]
from @tscholak ([gitter thread](https://gitter.im/suhailshergill/ProPL-meetup?at=57bb2925ed79c5ee4f28c788)):
- the loophole-free Bell inequality tests ([arxiv paper](https://arxiv.org/pdf/1508.05949v1.pdf))
- http://data.4tu.nl/repository/uuid:6e19e9b2-4a2d-40b5-8dd3-a660bf3c0a31 ( @tscholak can also be contacted for a copy)
- columns: 17
- rows: 4746
- density/sparsity: ???

**Comment by suhailshergill** [comment]
- data from the [kaggle titanic competition](https://www.kaggle.com/c/titanic). we also have some reference explorations on this dataset:
  - https://github.com/agconti/kaggle-titanic
  - http://wiekvoet.blogspot.ca/2015/07/predicting-titanic-deaths-on-kaggle.html and other blogs in the series. specifically http://wiekvoet.blogspot.ca/2015/09/predicting-titanic-deaths-on-kaggle-vi.html and https://www.r-bloggers.com/predicting-titanic-deaths-on-kaggle-vii-more-stan/ tries stan
  - https://www.kaggle.com/mrisdal/titanic/exploring-survival-on-the-titanic with a [reference submission](https://www.kaggle.com/benhamner/titanic/random-forest-benchmark-r/code) (one of many)
- a copy of the data can be found [here](https://github.com/agconti/kaggle-titanic/tree/master/data)
- columns: 11
- rows: 891
- density/sparsity: most attributes seem to have values for most entries. a notable exception is the column titled `Cabin`
- a [description of the data](https://www.kaggle.com/c/titanic/data)
  
  ```
  VARIABLE DESCRIPTIONS:
  survival        Survival
              (0 = No; 1 = Yes)
  pclass          Passenger Class
              (1 = 1st; 2 = 2nd; 3 = 3rd)
  name            Name
  sex             Sex
  age             Age
  sibsp           Number of Siblings/Spouses Aboard
  parch           Number of Parents/Children Aboard
  ticket          Ticket Number
  fare            Passenger Fare
  cabin           Cabin
  embarked        Port of Embarkation
              (C = Cherbourg; Q = Queenstown; S = Southampton)
  
  SPECIAL NOTES:
  Pclass is a proxy for socio-economic status (SES)
  1st ~ Upper; 2nd ~ Middle; 3rd ~ Lower
  
  Age is in Years; Fractional if Age less than One (1)
  If the Age is Estimated, it is in the form xx.5
  
  With respect to the family relation variables (i.e. sibsp and parch)
  some relations were ignored.  The following are the definitions used
  for sibsp and parch.
  
  Sibling:  Brother, Sister, Stepbrother, or Stepsister of Passenger Aboard Titanic
  Spouse:   Husband or Wife of Passenger Aboard Titanic (Mistresses and Fiances Ignored)
  Parent:   Mother or Father of Passenger Aboard Titanic
  Child:    Son, Daughter, Stepson, or Stepdaughter of Passenger Aboard Titanic
  
  Other family relatives excluded from this study include cousins,
  nephews/nieces, aunts/uncles, and in-laws.  Some children travelled
  only with a nanny, therefore parch=0 for them.  As well, some
  travelled with very close friends or neighbors in a village, however,
  the definitions do not support such relations.
  ```

**Comment by shabscan** [comment]
Efficient Market Theory(EMT) says that all public information is already embedded in Market prices and you cannot do better than a monkey throwing a dart to pick stock market winners. 

The goal is to look at financial data like stock market indices to validate/ debunk EMT. 

Sample QQQ prices from 2002-2016
[QQQ.txt](https://github.com/suhailshergill/ProPL-meetup/files/451723/QQQ.txt)
Date,Open,High,Low,Close,Volume,Adj Close

**Comment by suhailshergill** [comment]
@shabscan could you link to the dataset and characterize it via specifics as the previous comments do? Thanks!

**Comment by rcuevass** [comment]
What about something related with flight delay prediction?
- Data from the United States Department of Transportation 
- A copy of the data can be found [here](http://stat-computing.org/dataexpo/2009/the-data.html). We can choose a specific year. Specifically for year 2008:
- Columns: 29
- Rows:   ~7,000,000
- Density/Sparsity: ?

**Comment by suhailshergill** [comment]
@rcuevass have you tried any probabilistic programming system on a local laptop on that large a dataset?

**Comment by rcuevass** [comment]
@suhailshergill fair enough...I will try to consider another dataset

**Comment by rcuevass** [comment]
Energy efficiency dataset.
- The dataset can be found [here](https://archive.ics.uci.edu/ml/datasets/Energy+efficiency)
- Columns: 8 
- Rows: 768
- Density/Sparsity: ?

**Comment by rcuevass** [comment]
Brest Cancer Wisconsin Data Set
- Dataset found [here](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Original%29)
- Columns: 10
- Rows: 699
- Density/Sparsity: ?

**Comment by suhailshergill** [comment]
we have a winner! [the titanic dataset](https://github.com/suhailshergill/ProPL-meetup/issues/16#issuecomment-244038327)
